export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_COMPLETE = "AUTH_LOGOUT_COMPLETE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

/**
 * blames
 */

export const BLAME_LIST = 'BLAME_LIST';
export const GET_BLAME_SUCCESS = 'GET_BLAME_SUCCESS';
export const GET_BLAME_FAILURE = 'GET_BLAME_FAILURE';
