export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_CLEAR = "AUTH_CLEAR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_COMPLETE = "AUTH_LOGOUT_COMPLETE";

export const SESSION_CHECK = "SESSION_CHECK";
export const SESSION_ALIVE = "SESSION_ALIVE";
export const SESSION_EXPIRED = "SESSION_EXPIRED";

export const RESET_REDIRECT = " RESET_REDIRECT";

/**
 * blames
 */

export const BLAME_LIST = 'BLAME_LIST';
export const GET_BLAME_SUCCESS = 'GET_BLAME_SUCCESS';
export const GET_BLAME_FAILURE = 'GET_BLAME_FAILURE';
